wireplumber.components = [
    {
        name="90-steam-lostark-recording.lua"
        type=script/lua
        provides=custom.steam-lostark-recording
    }
]

wireplumber.profiles = {
    main = {
        custom.steam-lostark-recording = required
    }
}
